### ISSUE TITLE
Task list problems

### ISSUE THREAD

**Issue by petros** [githubhelp/playground#39]
###### XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- **XXXXXXXX**: XXXXXXXX
- **XXXXXXXX**: XXXXXXX

### XXXXXXX XXXXXXX 
- [x] **XXXXXXX XXXXXXX X**

     XXXXX                                 | XXXX          
    -----------------------------------------|---------------------
     XXXXXXXX                                 | `XXXXXXXXX.XXXX`
     XXXXX                          | `XXXXXXXXX.XXX`
     XXXXXXXXX                                | `XXXXXXX`
     XXXXXXXX XXXXXXX                        | `XXXX` 

- [ ] **XXXXXXXXXXX**

     XXXXXX                                 | XXXXX XXXX                   
    -----------------------------------------|--------------------------
     XXXXX                                | `XXXX`
     XXXXX                          | `XXXX`
     XXXXXXXXX                                | `XXXX`            
     XXXXXXXXX                        | `XXXX`            

### asdfasdf asdf
- [x] `asdfsadf` - [asfasdf]
- [ ] `asdfasdf` - [asdfasdf asdfasdf]

### Aasdfasdf asdfasdf
- [ ] **Sasdfasdf Aasdfsadf Nasdf**

     Sasdfasdf                                 | Sasdf asdf          
    -----------------------------------------|--------------------------
     Sasdfsadf asdfasdf nasdf                 | `asdf`

### asf asdf
- [ ] **Tasdfasdf asdfasdfsd**

     Sasdfasfd                                 | Sasdfsadf           
    -----------------------------------------|-----------------
     Lasdf                                    | asdf              
     Sasdfas asdf                                | asdf             
     Sasdfas  asdf asdf                             | asdf             
     Uasdf asf asdf asdf                   | asdf             
     Uasdfasf  as asdf sfd asdf                 | asfd
     Uasdf asdf asdf asdf dsf    | asfd
     Sasdff                           | asf
     Masdfsdf fsadf                               | asdf              
     Sasdf asdf                          | asfsd              

- [ ] **XXXX XXXXX XXXXXXXX**

     XXXXXXX                                 | XXX XX          
    -----------------------------------------|-----------------
     XXX XXX XXXXXXX XXXX                    | XXX             
     XXXX XXXX                               | XXXX            
     XXXX XXXXXX                             | `XXXX_XXXXX.XXX`

- [x] **XXXXXXXX XXXX XXXXXXXX**

     XXXXXXX                                 | XXX XX          
    -----------------------------------------|-----------------
     XXX XXX XXXXXXXX XXXX                   | XXX             
     XXXX XX XXXXXX XXXX                     | XXXX            
     XXXXXX XXXX XXXXX                       | `XXXX.XXX`      

- [x] **XXXX'X'XXXX**

     XXXXXXX                                 | XXX XX          
    -----------------------------------------|-----------------
     XXXXX XXXXXX                            | `XXXXXX`       

### XXXXXXXXXX & XXXXXXX XXXXXX
- [x] **XXXXXXXXXX**
```
XXXXXXXXXX XXXXXXXXXX

XXX XXXXXXXXXXX XXXXXXXXX XXXXXX XX XXX XXXXXXX XXXXXXXXX XXXX XXX XXXX XXX XXXXXXXXXX XX XXXXX XX XXXX XX XXXXXXX XXXXX XX XXX XXXXX XXXXXXXX XX XXXXXXX XXXXXXXXXXXXX.
XXXXXXXXXXX, XXXXXXXX XXXXXXXXXXX, XXXXXXXXXX XXXX XXX XXXXXXXX XXX XXX XX XXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXX.

XXXXXXXXXX XXXXX XXXX XXXXXX XXX XXXXXXXXXX XXX XXX XXX XXXXXXX XX XXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XX XX XXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXX. XXXXX XXX XX XX XXXXXXXXXX XXXX XXX XXXX XXXX XX XXXX XX XXXXXXXX XXX XXX XXXXX XXXXX XXX XXXXXXXX XX X XXXXXXXX XXXXXX XX XXXX XXX XXXX XXXXXX XX XXXX XXXXXXXXXX XX XXX XXXX XXXX XX XXXXXXXX XX XXX. XXXX XXXXXX XXXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXX XXX XXX XX XXXXXXXX.

XXXXXXXXX XXXXXXXXXX

XXXX XXXXXXX XXX XXXX XXXXX XXXXXXXXX XXXXXXX XXXXXXXX, XXX XX XXXXXXXX XXXXXXXX; XXXXXXXX XXXX XXXX XXX XXXX XXXXXXXXXX XX XX XX XXXXX XXXXXXXXXX XXXXXXXXXXX XXX XXX XXXXXX XXXXXXXX XXXX XXXXXXXX XX XX XXXXXXXXX XXXXXXX XX XXX XXXXXX. XXX XXXXXXXXXX XXXXXXX XX XXXX XXXXX XXXXXXXXXX XXX XXX XXX XXXXXXXX XX XXX XXXXXX XXX XXX XXX XXX XXXXXXXXXXXXXX XX XXX XXXXXX.
```
- [ ] **XXXXXXX XXXXXX**
```
XXXXXXXX XXXXXXX XXXXXX

XXXXXXXX XXXXXXX XX XXXXXXXXX XX XXXXXXXXXX XXX XXXXXXX XX XXXXXXXXXXX XXX XXXXXXXXXX XXX XXXX XX XXXXXX XXXX XXXX XX XX XXXXXXXX XXX XXXXXXXXX XXX XXX XXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XX XXX XXXXXXXX XXXXXXXXXXX XXXX XXX XXXXX XX XXXXXXX XX XX.

XXX XXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX XX XXX XXXXXXXXXX, XXXXXXX, XXX XXX XXXXXXXXX XX XXXX XXXXXXXX XXXXXXXXXXX XX XXXXXXX:

XXXXXXXXXX: XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX (XXXXXXX, XXXXXXXXX, XXXXXXXXX, XXX) XX XXXXX XX XXXXXX XXXXXX XXX XXXXXXXX. XXX XXXXXXXXXXXX XXXX XXXX XXX XXXXXXXXXX XXXXXXX XX XXXXX XXXXXX XXXX XXXXXXXXXXX XXXXX XXX XXXXXXX XXX/XXXXXXXXXX. XXX XXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXXXX XXX XXX XX XXXXXXXX XXXXXXXXXXX XX XXXX XXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXX XX XX XXXXXX XXXX XXXXXXXXXXX.

XXXXXXXX: XXX XXXXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXX XXXXXX XX XXXXXX XXXX XXX XXXXXXXX XXXXXXXXXXX XX XXXXXXXX XXX XXXX XX XXXXXXXX XXX XXXXXXXX. XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXX XXX XXXXXXXXXXX XX XXXXXX XXX XXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX, XXX XX XXXXXXX XXXXXXX XX XX XXXXXXXXXX XX XXXX XXX XXXXXXXXXXX XXXXXXX, XXX XXXXXXXXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XX XXXXXXXX.

XXXXXXX: XXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXX XXX/XX XXXXXXXXXX XXXXX XX XXXX X XXX XX XX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX, XXXXXX, XXX, XXXXXXXXXX XX XXXXXXXX XX XXX XXXXXXXX XXXXXXXXXXX.

XXXXXXXXX: XXX XXXXXXXXXXXX XXXX XXXXXXXXX X XXXXXXXXX XXXXXX XXX XXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX. XXXX XXXXXX XXX XX XXXXXXX XX XXXXXXXXXXX XXXXX XXXX XXXXXX (XXXXXXXXXX XXXXXXXXX XXX XXXXXXX).

XXXXXXXXXX: XXX XXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXX XX XXX XXXXX XXXXX, XXXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXX.

XXXXXX: XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX’X XXXXX XX XXXXXX XX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX. XXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXX XX XXXXXXXXXXX XXXX XXXXXXX. XXXXXX XXXX XX XXXXXXXX XXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXX. XXXX: XXXXXX XX X XXXXXX XXX XX XXXXXXX XX XXX XXXXXXX XX X XXX XXXXXX XXX XX XXXXXX XX XXX XXXXXXXXXXXX.

XX XXXXXXXX XX XXX XXXX XXXX XXXXXXXX XXXXXXX XXXXX XXXXXXXX, XX XXX XXXX XXXXXXX XXXX XXX XX XXX XXXXXXX XXXXXXXXXXXXX XXXX XXX XX XXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXX XX XX XX XXX XXXXXX XX XXXXX XXXXXXXXXXXX XXXX XXX XXXXXXX XX XX. XXXX XXXXX XXXXX XXXXXXX XXX XXXXXX XX XXXX XXX XXXXXXXXX XX XXXXXXX, XXXXXXXXXXXXXXX XXX XXXXXXXX.

XXX XXXXXXXXX XXX XXXXX XXXXX XXXXX XXX XX XXX XXX XXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXX XXXXXX XX XXXXXX XX XXX XXXXXXX XXXX XXX XXX XXXXXXXXXX XXXX XXXXXXX XXXX XXXX.

XXX XXXXXXX XXXXXXXXXXX XXXXXXX:

XXXXXXX XXXXXXX: XXXXXXXX XXXXXXX
XXXXX: (XXX) XXX-XXXX
XXXXX: XXXXXXXXXXXXXXXXXXXXXX.XXX 

XXX XXX XXXX XXXXXXX XXX XXXXXX XX XXX XXXXXXX XXXXXXXXXXXX XX XXXXXX XXX XXXXXXXXXX XXXXXXX XXX XXXXX XX X XX XXX X XX, XX:

XXXX-XXXX: X-XXX-XXX-XXXX
XXXXX: (XXX) XXX-XXXX
XXX: (XXX) XXX-XXXX
XX XX XXXX XX:
XXX XXXX XXXXXX
XXXXX XX XXXXX
XXXXX X, XXX XXXXX
XXXXXX, XXXXXXX
XXX XXX
XX XX XXX XXX XX: XXXX://XXX.XXXXXXX.XX.XX/
```

### XXX XXXX XXXXXX
- [x] `XXXXXXXXXXXXXXXXXXX.XXX` X-XXXX XX XXXXXXX

### XXXXXXXXXX XXXX
> XXXXXX XXXX X XXXXXXX XX XXX XXXXXX XX XXX XXXX XX XXXXXXXX XX XXXXXXX XXX XXXXXXXXXX XXXXXX XX XX XXX XXXXXXXX.

- [ ] **XXXXXXX XXXX XXXXXXXXXX XXXXXX XX:**

     XXXXXXXXX                               | XXXXXX          
    -----------------------------------------|-----------------
     XXXXXX_XXXX                             | `XXXX`          
     XXXXXX XXXX XXXXX                       | `XXXX`           
     XXXXXX XXXX XXXX                        | `XXX`             

### XXXXXX XXXXXXXXXX
- [x] **XXXXX XX XXX XXXXXX XXXXXXXXXX XX XXXXXXXXX. XX XXXXXX XX:**

```
XXXX
```

### XXXXXXXXX XXXXXX XXXX
- [ ] **XXXXXXX XXXXXXX**
    - XXXXX XXXXXX
    - XXX XXXX XXXXXXXXXXXX
    - XXXXXXXX XXXX / XXXXXXXX XXXXX
    - XXXXXXXXX XXXXXXX / XXXX XXXXXXX

[XXXXX]: XXXX://XXXXXXXXXXXXXX.XXXXXXXXXX.XXX/XXXX/XXXXX
[XXXX XXXX XXXX]: XXXXX://XXXXXX.XXX/XXXXXXXXXX/XXXXXX/XXXX/XXXXXX-XXXX-XXXXXXXXXXX#XXXX-XXXX
[XXXXXX XXXX]: XXXXX://XXXXXX.XXX/XXXXXXXXXX/XXXXXX/XXXX/XXXXXX-XXXX-XXXXXXXXXXX#XXXXXX

**Comment by petros** [comment]
### XXXXXXXXX XXXXXX XXXX

- [ ] **XXXXXXX XXXXXXX**

    - XXXXX XXXXXX
    - XXX XXXX XXXXXXXXXXXX
    - XXXXXXXX XXXX / XXXXXXXX XXXXX
    - XXXXXXXXX XXXXXXX / XXXX XXXXXXX
